[package]
name = "untitled-1"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
gif = "0.13.1"
hex_color = "3.0.0"
image = "0.25.5"
log = "0.4.25"
rand = "0.9.0"
simple_logger = "5.0.0"

[profile.release]
debug = 1
